#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-AU-* : Audit Policy  (ASCII comments only - PS 5.1 safe)
# ==========================================================

# WN11-AU-000005
try {
    $auditLine = (auditpol /get /subcategory:'Credential Validation' 2>&1) | Where-Object { $_ -match 'Credential Validation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000005' `
        -Title        'The system must be configured to audit Account Logon - Credential Validation failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Credential Validation'" `
        -Fix          'auditpol /set /subcategory:'Credential Validation' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Credential Validation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000005' 'The system must be configured to audit Account Logon - Credential Validation failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000010
try {
    $auditLine = (auditpol /get /subcategory:'Credential Validation' 2>&1) | Where-Object { $_ -match 'Credential Validation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000010' `
        -Title        'The system must be configured to audit Account Logon - Credential Validation successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Credential Validation'" `
        -Fix          'auditpol /set /subcategory:'Credential Validation' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Credential Validation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000010' 'The system must be configured to audit Account Logon - Credential Validation successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000030
try {
    $auditLine = (auditpol /get /subcategory:'Security Group Management' 2>&1) | Where-Object { $_ -match 'Security Group Management' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000030' `
        -Title        'The system must be configured to audit Account Management - Security Group Management successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Security Group Management'" `
        -Fix          'auditpol /set /subcategory:'Security Group Management' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Security Group Management: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000030' 'The system must be configured to audit Account Management - Security Group Management successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000035
try {
    $auditLine = (auditpol /get /subcategory:'User Account Management' 2>&1) | Where-Object { $_ -match 'User Account Management' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000035' `
        -Title        'The system must be configured to audit Account Management - User Account Management failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'User Account Management'" `
        -Fix          'auditpol /set /subcategory:'User Account Management' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'User Account Management: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000035' 'The system must be configured to audit Account Management - User Account Management failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000040
try {
    $auditLine = (auditpol /get /subcategory:'User Account Management' 2>&1) | Where-Object { $_ -match 'User Account Management' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000040' `
        -Title        'The system must be configured to audit Account Management - User Account Management successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'User Account Management'" `
        -Fix          'auditpol /set /subcategory:'User Account Management' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'User Account Management: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000040' 'The system must be configured to audit Account Management - User Account Management successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000045
try {
    $auditLine = (auditpol /get /subcategory:'Plug and Play Events' 2>&1) | Where-Object { $_ -match 'Plug and Play Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000045' `
        -Title        'The system must be configured to audit Detailed Tracking - PNP Activity successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Plug and Play Events'" `
        -Fix          'auditpol /set /subcategory:'Plug and Play Events' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Plug and Play Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000045' 'The system must be configured to audit Detailed Tracking - PNP Activity successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000050
try {
    $auditLine = (auditpol /get /subcategory:'Process Creation' 2>&1) | Where-Object { $_ -match 'Process Creation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000050' `
        -Title        'The system must be configured to audit Detailed Tracking - Process Creation successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Process Creation'" `
        -Fix          'auditpol /set /subcategory:'Process Creation' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Process Creation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000050' 'The system must be configured to audit Detailed Tracking - Process Creation successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000054
try {
    $auditLine = (auditpol /get /subcategory:'Account Lockout' 2>&1) | Where-Object { $_ -match 'Account Lockout' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000054' `
        -Title        'The system must be configured to audit Logon/Logoff - Account Lockout failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Account Lockout'" `
        -Fix          'auditpol /set /subcategory:'Account Lockout' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Account Lockout: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000054' 'The system must be configured to audit Logon/Logoff - Account Lockout failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000060
try {
    $auditLine = (auditpol /get /subcategory:'Group Membership' 2>&1) | Where-Object { $_ -match 'Group Membership' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000060' `
        -Title        'The system must be configured to audit Logon/Logoff - Group Membership successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Group Membership'" `
        -Fix          'auditpol /set /subcategory:'Group Membership' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Group Membership: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000060' 'The system must be configured to audit Logon/Logoff - Group Membership successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000065
try {
    $auditLine = (auditpol /get /subcategory:'Logoff' 2>&1) | Where-Object { $_ -match 'Logoff' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000065' `
        -Title        'The system must be configured to audit Logon/Logoff - Logoff successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Logoff'" `
        -Fix          'auditpol /set /subcategory:'Logoff' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Logoff: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000065' 'The system must be configured to audit Logon/Logoff - Logoff successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000070
try {
    $auditLine = (auditpol /get /subcategory:'Logon' 2>&1) | Where-Object { $_ -match 'Logon' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000070' `
        -Title        'The system must be configured to audit Logon/Logoff - Logon failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Logon'" `
        -Fix          'auditpol /set /subcategory:'Logon' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Logon: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000070' 'The system must be configured to audit Logon/Logoff - Logon failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000075
try {
    $auditLine = (auditpol /get /subcategory:'Logon' 2>&1) | Where-Object { $_ -match 'Logon' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000075' `
        -Title        'The system must be configured to audit Logon/Logoff - Logon successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Logon'" `
        -Fix          'auditpol /set /subcategory:'Logon' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Logon: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000075' 'The system must be configured to audit Logon/Logoff - Logon successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000080
try {
    $auditLine = (auditpol /get /subcategory:'Special Logon' 2>&1) | Where-Object { $_ -match 'Special Logon' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000080' `
        -Title        'The system must be configured to audit Logon/Logoff - Special Logon successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Special Logon'" `
        -Fix          'auditpol /set /subcategory:'Special Logon' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Special Logon: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000080' 'The system must be configured to audit Logon/Logoff - Special Logon successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000081
try {
    $auditLine = (auditpol /get /subcategory:'File Share' 2>&1) | Where-Object { $_ -match 'File Share' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000081' `
        -Title        'Windows 11 must be configured to audit Object Access - File Share failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'File Share'" `
        -Fix          'auditpol /set /subcategory:'File Share' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'File Share: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000081' 'Windows 11 must be configured to audit Object Access - File Share failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000082
try {
    $auditLine = (auditpol /get /subcategory:'File Share' 2>&1) | Where-Object { $_ -match 'File Share' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000082' `
        -Title        'Windows 11 must be configured to audit Object Access - File Share successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'File Share'" `
        -Fix          'auditpol /set /subcategory:'File Share' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'File Share: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000082' 'Windows 11 must be configured to audit Object Access - File Share successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000083
try {
    $auditLine = (auditpol /get /subcategory:'Other Object Access Events' 2>&1) | Where-Object { $_ -match 'Other Object Access Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000083' `
        -Title        'Windows 11 must be configured to audit Object Access - Other Object Access Events successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other Object Access Events'" `
        -Fix          'auditpol /set /subcategory:'Other Object Access Events' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Other Object Access Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000083' 'Windows 11 must be configured to audit Object Access - Other Object Access Events successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000084
try {
    $auditLine = (auditpol /get /subcategory:'Other Object Access Events' 2>&1) | Where-Object { $_ -match 'Other Object Access Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000084' `
        -Title        'Windows 11 must be configured to audit Object Access - Other Object Access Events failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other Object Access Events'" `
        -Fix          'auditpol /set /subcategory:'Other Object Access Events' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Other Object Access Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000084' 'Windows 11 must be configured to audit Object Access - Other Object Access Events failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000085
try {
    $auditLine = (auditpol /get /subcategory:'Removable Storage' 2>&1) | Where-Object { $_ -match 'Removable Storage' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000085' `
        -Title        'The system must be configured to audit Object Access - Removable Storage failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Removable Storage'" `
        -Fix          'auditpol /set /subcategory:'Removable Storage' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Removable Storage: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000085' 'The system must be configured to audit Object Access - Removable Storage failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000090
try {
    $auditLine = (auditpol /get /subcategory:'Removable Storage' 2>&1) | Where-Object { $_ -match 'Removable Storage' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000090' `
        -Title        'The system must be configured to audit Object Access - Removable Storage successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Removable Storage'" `
        -Fix          'auditpol /set /subcategory:'Removable Storage' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Removable Storage: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000090' 'The system must be configured to audit Object Access - Removable Storage successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000100
try {
    $auditLine = (auditpol /get /subcategory:'Audit Policy Change' 2>&1) | Where-Object { $_ -match 'Audit Policy Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000100' `
        -Title        'The system must be configured to audit Policy Change - Audit Policy Change successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Audit Policy Change'" `
        -Fix          'auditpol /set /subcategory:'Audit Policy Change' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Audit Policy Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000100' 'The system must be configured to audit Policy Change - Audit Policy Change successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000105
try {
    $auditLine = (auditpol /get /subcategory:'Authentication Policy Change' 2>&1) | Where-Object { $_ -match 'Authentication Policy Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000105' `
        -Title        'The system must be configured to audit Policy Change - Authentication Policy Change successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Authentication Policy Change'" `
        -Fix          'auditpol /set /subcategory:'Authentication Policy Change' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Authentication Policy Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000105' 'The system must be configured to audit Policy Change - Authentication Policy Change successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000107
try {
    $auditLine = (auditpol /get /subcategory:'Authorization Policy Change' 2>&1) | Where-Object { $_ -match 'Authorization Policy Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000107' `
        -Title        'The system must be configured to audit Policy Change - Authorization Policy Change successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Authorization Policy Change'" `
        -Fix          'auditpol /set /subcategory:'Authorization Policy Change' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Authorization Policy Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000107' 'The system must be configured to audit Policy Change - Authorization Policy Change successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000110
try {
    $auditLine = (auditpol /get /subcategory:'Sensitive Privilege Use' 2>&1) | Where-Object { $_ -match 'Sensitive Privilege Use' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000110' `
        -Title        'The system must be configured to audit Privilege Use - Sensitive Privilege Use failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Sensitive Privilege Use'" `
        -Fix          'auditpol /set /subcategory:'Sensitive Privilege Use' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Sensitive Privilege Use: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000110' 'The system must be configured to audit Privilege Use - Sensitive Privilege Use failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000115
try {
    $auditLine = (auditpol /get /subcategory:'Sensitive Privilege Use' 2>&1) | Where-Object { $_ -match 'Sensitive Privilege Use' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000115' `
        -Title        'The system must be configured to audit Privilege Use - Sensitive Privilege Use successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Sensitive Privilege Use'" `
        -Fix          'auditpol /set /subcategory:'Sensitive Privilege Use' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Sensitive Privilege Use: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000115' 'The system must be configured to audit Privilege Use - Sensitive Privilege Use successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000120
try {
    $auditLine = (auditpol /get /subcategory:'IPsec Driver' 2>&1) | Where-Object { $_ -match 'IPsec Driver' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000120' `
        -Title        'The system must be configured to audit System - IPsec Driver failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'IPsec Driver'" `
        -Fix          'auditpol /set /subcategory:'IPsec Driver' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'IPsec Driver: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000120' 'The system must be configured to audit System - IPsec Driver failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000130
try {
    $auditLine = (auditpol /get /subcategory:'Other System Events' 2>&1) | Where-Object { $_ -match 'Other System Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000130' `
        -Title        'The system must be configured to audit System - Other System Events successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other System Events'" `
        -Fix          'auditpol /set /subcategory:'Other System Events' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Other System Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000130' 'The system must be configured to audit System - Other System Events successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000135
try {
    $auditLine = (auditpol /get /subcategory:'Other System Events' 2>&1) | Where-Object { $_ -match 'Other System Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000135' `
        -Title        'The system must be configured to audit System - Other System Events failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other System Events'" `
        -Fix          'auditpol /set /subcategory:'Other System Events' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Other System Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000135' 'The system must be configured to audit System - Other System Events failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000140
try {
    $auditLine = (auditpol /get /subcategory:'Security State Change' 2>&1) | Where-Object { $_ -match 'Security State Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000140' `
        -Title        'The system must be configured to audit System - Security State Change successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Security State Change'" `
        -Fix          'auditpol /set /subcategory:'Security State Change' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Security State Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000140' 'The system must be configured to audit System - Security State Change successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000150
try {
    $auditLine = (auditpol /get /subcategory:'Security System Extension' 2>&1) | Where-Object { $_ -match 'Security System Extension' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000150' `
        -Title        'The system must be configured to audit System - Security System Extension successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Security System Extension'" `
        -Fix          'auditpol /set /subcategory:'Security System Extension' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Security System Extension: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000150' 'The system must be configured to audit System - Security System Extension successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000155
try {
    $auditLine = (auditpol /get /subcategory:'System Integrity' 2>&1) | Where-Object { $_ -match 'System Integrity' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000155' `
        -Title        'The system must be configured to audit System - System Integrity failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'System Integrity'" `
        -Fix          'auditpol /set /subcategory:'System Integrity' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'System Integrity: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000155' 'The system must be configured to audit System - System Integrity failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000160
try {
    $auditLine = (auditpol /get /subcategory:'System Integrity' 2>&1) | Where-Object { $_ -match 'System Integrity' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000160' `
        -Title        'The system must be configured to audit System - System Integrity successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'System Integrity'" `
        -Fix          'auditpol /set /subcategory:'System Integrity' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'System Integrity: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000160' 'The system must be configured to audit System - System Integrity successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000555
try {
    $auditLine = (auditpol /get /subcategory:'Other Policy Change Events' 2>&1) | Where-Object { $_ -match 'Other Policy Change Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000555' `
        -Title        'Windows 11 must be configured to audit Other Policy Change Events Failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other Policy Change Events'" `
        -Fix          'auditpol /set /subcategory:'Other Policy Change Events' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Other Policy Change Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000555' 'Windows 11 must be configured to audit Other Policy Change Events Failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000560
try {
    $auditLine = (auditpol /get /subcategory:'Other Logon/Logoff Events' 2>&1) | Where-Object { $_ -match 'Other Logon/Logoff Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000560' `
        -Title        'Windows 11 must be configured to audit other Logon/Logoff Events Successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other Logon/Logoff Events'" `
        -Fix          'auditpol /set /subcategory:'Other Logon/Logoff Events' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Other Logon/Logoff Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000560' 'Windows 11 must be configured to audit other Logon/Logoff Events Successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000565
try {
    $auditLine = (auditpol /get /subcategory:'Other Logon/Logoff Events' 2>&1) | Where-Object { $_ -match 'Other Logon/Logoff Events' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000565' `
        -Title        'Windows 11 must be configured to audit other Logon/Logoff Events Failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Other Logon/Logoff Events'" `
        -Fix          'auditpol /set /subcategory:'Other Logon/Logoff Events' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Other Logon/Logoff Events: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000565' 'Windows 11 must be configured to audit other Logon/Logoff Events Failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000570
try {
    $auditLine = (auditpol /get /subcategory:'Detailed File Share' 2>&1) | Where-Object { $_ -match 'Detailed File Share' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000570' `
        -Title        'Windows 11 must be configured to audit Detailed File Share Failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Detailed File Share'" `
        -Fix          'auditpol /set /subcategory:'Detailed File Share' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Detailed File Share: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000570' 'Windows 11 must be configured to audit Detailed File Share Failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000575
try {
    $auditLine = (auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change' 2>&1) | Where-Object { $_ -match 'MPSSVC Rule-Level Policy Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000575' `
        -Title        'Windows 11 must be configured to audit MPSSVC Rule-Level Policy Change Successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change'" `
        -Fix          'auditpol /set /subcategory:'MPSSVC Rule-Level Policy Change' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'MPSSVC Rule-Level Policy Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000575' 'Windows 11 must be configured to audit MPSSVC Rule-Level Policy Change Successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000580
try {
    $auditLine = (auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change' 2>&1) | Where-Object { $_ -match 'MPSSVC Rule-Level Policy Change' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000580' `
        -Title        'Windows 11 must be configured to audit MPSSVC Rule-Level Policy Change Failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change'" `
        -Fix          'auditpol /set /subcategory:'MPSSVC Rule-Level Policy Change' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'MPSSVC Rule-Level Policy Change: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000580' 'Windows 11 must be configured to audit MPSSVC Rule-Level Policy Change Failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000581
try {
    $auditLine = (auditpol /get /subcategory:'File System' 2>&1) | Where-Object { $_ -match 'File System' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000581' `
        -Title        'Windows 11 must be configured to audit file system failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'File System'" `
        -Fix          'auditpol /set /subcategory:'File System' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'File System: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000581' 'Windows 11 must be configured to audit file system failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000582
try {
    $auditLine = (auditpol /get /subcategory:'File System' 2>&1) | Where-Object { $_ -match 'File System' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000582' `
        -Title        'Windows 11 must be configured to audit file system successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'File System'" `
        -Fix          'auditpol /set /subcategory:'File System' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'File System: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000582' 'Windows 11 must be configured to audit file system successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000583
try {
    $auditLine = (auditpol /get /subcategory:'Handle Manipulation' 2>&1) | Where-Object { $_ -match 'Handle Manipulation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000583' `
        -Title        'Windows 11 must be configured to audit handle manipulation failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Handle Manipulation'" `
        -Fix          'auditpol /set /subcategory:'Handle Manipulation' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Handle Manipulation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000583' 'Windows 11 must be configured to audit handle manipulation failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000584
try {
    $auditLine = (auditpol /get /subcategory:'Handle Manipulation' 2>&1) | Where-Object { $_ -match 'Handle Manipulation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000584' `
        -Title        'Windows 11 must be configured to audit handle manipulation successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Handle Manipulation'" `
        -Fix          'auditpol /set /subcategory:'Handle Manipulation' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Handle Manipulation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000584' 'Windows 11 must be configured to audit handle manipulation successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000585
try {
    $auditLine = (auditpol /get /subcategory:'Process Creation' 2>&1) | Where-Object { $_ -match 'Process Creation' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000585' `
        -Title        'Windows 11 must have command line process auditing events enabled for failures.' `
        -Severity     'CAT_II' `
        -Description  'When this policy setting is enabled, the operating system generates audit events when a process fails to start and the name of the program or user that created it. These audit events can assist in und' `
        -Check        "auditpol /get /subcategory:'Process Creation'" `
        -Fix          'auditpol /set /subcategory:'Process Creation' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Process Creation: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000585' 'Windows 11 must have command line process auditing events enabled for failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000586
try {
    $auditLine = (auditpol /get /subcategory:'Registry' 2>&1) | Where-Object { $_ -match 'Registry' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000586' `
        -Title        'Windows 11 must be configured to audit registry successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Registry'" `
        -Fix          'auditpol /set /subcategory:'Registry' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Registry: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000586' 'Windows 11 must be configured to audit registry successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000587
try {
    $auditLine = (auditpol /get /subcategory:'Sensitive Privilege Use' 2>&1) | Where-Object { $_ -match 'Sensitive Privilege Use' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Success","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000587' `
        -Title        'Windows 11 must be configured to audit sensitive privilege use successes.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Sensitive Privilege Use'" `
        -Fix          'auditpol /set /subcategory:'Sensitive Privilege Use' /success:enable' `
        -PassCriteria 'includes Success' `
        -Status       $status `
        -Evidence     'Sensitive Privilege Use: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000587' 'Windows 11 must be configured to audit sensitive privilege use successes.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000588
try {
    $auditLine = (auditpol /get /subcategory:'Sensitive Privilege Use' 2>&1) | Where-Object { $_ -match 'Sensitive Privilege Use' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000588' `
        -Title        'Windows 11 must be configured to audit sensitive privilege use failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Sensitive Privilege Use'" `
        -Fix          'auditpol /set /subcategory:'Sensitive Privilege Use' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Sensitive Privilege Use: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000588' 'Windows 11 must be configured to audit sensitive privilege use failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000589
try {
    $auditLine = (auditpol /get /subcategory:'Registry' 2>&1) | Where-Object { $_ -match 'Registry' }
    $val = if ($auditLine) {
        if ($auditLine -match 'Success and Failure') { 'Success and Failure' }
        elseif ($auditLine -match 'Success') { 'Success' }
        elseif ($auditLine -match 'Failure') { 'Failure' }
        else { 'No Auditing' }
    } else { 'Unknown' }
    $status = if ($val -in "Failure","Success and Failure") { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000589' `
        -Title        'Windows 11 must be configured to audit registry failures.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        "auditpol /get /subcategory:'Registry'" `
        -Fix          'auditpol /set /subcategory:'Registry' /failure:enable' `
        -PassCriteria 'includes Failure' `
        -Status       $status `
        -Evidence     'Registry: ' + $val
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000589' 'Windows 11 must be configured to audit registry failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000500
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application' -Name 'MaxSize' -ErrorAction SilentlyContinue).MaxSize
    $status = if ($null -ne $val -and [int]$val -ge 32768) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000500' `
        -Title        'The Application event log size must be configured to 32768 KB or greater.' `
        -Severity     'CAT_II' `
        -Description  'Inadequate log size will cause the log to fill up quickly. This may prevent audit events from being recorded properly and require frequent attention by administrative personnel. false</Doc' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application -> MaxSize' `
        -Fix          'If the system is configured to send audit records directly to an audit server, this is NA. This must be documented with the ISSO. Configure the policy value for Computer Configuration >> Administrativ' `
        -PassCriteria 'Value >= 32768' `
        -Status       $status `
        -Evidence     "MaxSize = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000500' 'The Application event log size must be configured to 32768 KB or greater.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000505
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security' -Name 'MaxSize' -ErrorAction SilentlyContinue).MaxSize
    $status = if ($null -ne $val -and [int]$val -ge 196608) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000505' `
        -Title        'The security event log size must be configured to a value that holds at least one week''s worth of audit records.' `
        -Severity     'CAT_II' `
        -Description  'Inadequate log size will cause the log to fill up quickly. This may prevent audit events from being recorded properly and require frequent attention by administrative personnel. System administrators ' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security -> MaxSize' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> Windows Components >> Event Log Service >> Security >> `"Specify the maximum log file size (KB)`" to `"Enabled`" wi' `
        -PassCriteria 'Value >= 196608' `
        -Status       $status `
        -Evidence     "MaxSize = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000505' 'The security event log size must be configured to a value that holds at least one week''s worth of audit records.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000510
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\System' -Name 'MaxSize' -ErrorAction SilentlyContinue).MaxSize
    $status = if ($null -ne $val -and [int]$val -ge 32768) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000510' `
        -Title        'The System event log size must be configured to 32768 KB or greater.' `
        -Severity     'CAT_II' `
        -Description  'Inadequate log size will cause the log to fill up quickly. This may prevent audit events from being recorded properly and require frequent attention by administrative personnel. false</Doc' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\System -> MaxSize' `
        -Fix          'If the system is configured to send audit records directly to an audit server, this is NA. This must be documented with the ISSO. Configure the policy value for Computer Configuration >> Administrativ' `
        -PassCriteria 'Value >= 32768' `
        -Status       $status `
        -Evidence     "MaxSize = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000510' 'The System event log size must be configured to 32768 KB or greater.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000515
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000515' `
        -Title        'Windows 11 permissions for the Application event log must prevent access by non-privileged accounts.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audit logs are necessary to provide a trail of evidence in case the system or network is' `
        -Check        '' `
        -Fix          'Ensure the permissions on the Application event log (Application.evtx) are configured to prevent standard user accounts or groups from having access. The default permissions listed below satisfy this ' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000515' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000520
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000520' `
        -Title        'Windows 11 permissions for the Security event log must prevent access by non-privileged accounts.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audit logs are necessary to provide a trail of evidence in case the system or network is' `
        -Check        '' `
        -Fix          'Ensure the permissions on the Security event log (Security.evtx) are configured to prevent standard user accounts or groups from having access. The default permissions listed below satisfy this requir' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000520' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000525
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000525' `
        -Title        'Windows 11 permissions for the System event log must prevent access by non-privileged accounts.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audit logs are necessary to provide a trail of evidence in case the system or network is' `
        -Check        '' `
        -Fix          'Ensure the permissions on the System event log (System.evtx) are configured to prevent standard user accounts or groups from having access. The default permissions listed below satisfy this requiremen' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000525' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-AU-000585
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled' -ErrorAction SilentlyContinue).ProcessCreationIncludeCmdLine_Enabled
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-AU-000585' `
        -Title        'Windows 11 must have command line process auditing events enabled for failures.' `
        -Severity     'CAT_II' `
        -Description  'When this policy setting is enabled, the operating system generates audit events when a process fails to start and the name of the program or user that created it. These audit events can assist in und' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit -> ProcessCreationIncludeCmdLine_Enabled' `
        -Fix          'Go to Computer Configuration >> Windows Settings >>Security Settings>> Advanced Audit Policy Configuration >> System Audit Policies >> Detailed Tracking >> Set `"Audit Process Creation`" to `"Failure`' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "ProcessCreationIncludeCmdLine_Enabled = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-AU-000585' 'Windows 11 must have command line process auditing events enabled for failures.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
return $findings
