#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-SO-* : Security Options
# ==========================================================

# WN11-SO-000030
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'SCENoApplyLegacyAuditPolicy' -ErrorAction SilentlyContinue).SCENoApplyLegacyAuditPolicy
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000030' `
        -Title        'Audit policy using subcategories must be enabled.' `
        -Severity     'CAT_II' `
        -Description  'Maintaining an audit trail of system activity logs can help identify configuration errors, troubleshoot service disruptions, and analyze compromises that have occurred, as well as detect attacks. Audi' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> SCENoApplyLegacyAuditPolicy' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Audit: Force audit policy subcategory settings (Windows Vista ' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "SCENoApplyLegacyAuditPolicy = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000030' 'Audit policy using subcategories must be enabled.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000035
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'RequireSignOrSeal' -ErrorAction SilentlyContinue).RequireSignOrSeal
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000035' `
        -Title        'Outgoing secure channel traffic must be encrypted or signed.' `
        -Severity     'CAT_II' `
        -Description  'Requests sent on the secure channel are authenticated, and sensitive information (such as passwords) is encrypted, but not all information is encrypted. If this policy is enabled, outgoing secure chan' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> RequireSignOrSeal' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Domain member: Digitally encrypt or sign secure channel data (' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RequireSignOrSeal = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000035' 'Outgoing secure channel traffic must be encrypted or signed.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000040
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'SealSecureChannel' -ErrorAction SilentlyContinue).SealSecureChannel
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000040' `
        -Title        'Outgoing secure channel traffic must be encrypted.' `
        -Severity     'CAT_II' `
        -Description  'Requests sent on the secure channel are authenticated, and sensitive information (such as passwords) is encrypted, but not all information is encrypted. If this policy is enabled, outgoing secure chan' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> SealSecureChannel' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Domain member: Digitally encrypt secure channel data (when pos' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "SealSecureChannel = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000040' 'Outgoing secure channel traffic must be encrypted.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000045
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'SignSecureChannel' -ErrorAction SilentlyContinue).SignSecureChannel
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000045' `
        -Title        'Outgoing secure channel traffic must be signed.' `
        -Severity     'CAT_II' `
        -Description  'Requests sent on the secure channel are authenticated, and sensitive information (such as passwords) is encrypted, but the channel is not integrity checked. If this policy is enabled, outgoing secure ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> SignSecureChannel' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Domain member: Digitally sign secure channel data (when possib' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "SignSecureChannel = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000045' 'Outgoing secure channel traffic must be signed.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000050
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'DisablePasswordChange' -ErrorAction SilentlyContinue).DisablePasswordChange
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000050' `
        -Title        'The computer account password must not be prevented from being reset.' `
        -Severity     'CAT_III' `
        -Description  'Computer account passwords are changed automatically on a regular basis. Disabling automatic password changes can make the system more vulnerable to malicious access. Frequent password changes can be ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> DisablePasswordChange' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Domain member: Disable machine account password changes`" to `' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "DisablePasswordChange = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000050' 'The computer account password must not be prevented from being reset.' 'CAT_III' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000055
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'MaximumPasswordAge' -ErrorAction SilentlyContinue).MaximumPasswordAge
    $status = if ($null -ne $val -and [int]$val -le 30) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000055' `
        -Title        'The maximum age for machine account passwords must be configured to 30 days or less.' `
        -Severity     'CAT_III' `
        -Description  'Computer account passwords are changed automatically on a regular basis. This setting controls the maximum password age that a machine account may have. This setting must be set to no more than 30 day' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge' `
        -Fix          'This is the default configuration for this setting (30 days). Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"' `
        -PassCriteria 'Value <= 30' `
        -Status       $status `
        -Evidence     "MaximumPasswordAge = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000055' 'The maximum age for machine account passwords must be configured to 30 days or less.' 'CAT_III' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000060
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -Name 'RequireStrongKey' -ErrorAction SilentlyContinue).RequireStrongKey
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000060' `
        -Title        'The system must be configured to require a strong session key.' `
        -Severity     'CAT_II' `
        -Description  'A computer connecting to a domain controller will establish a secure channel. Requiring strong session keys enforces 128-bit encryption between systems. false </' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -> RequireStrongKey' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Domain member: Require strong (Windows 2000 or Later) session ' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RequireStrongKey = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000060' 'The system must be configured to require a strong session key.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000070
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'InactivityTimeoutSecs' -ErrorAction SilentlyContinue).InactivityTimeoutSecs
    $status = if ($null -ne $val -and [int]$val -le 900) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000070' `
        -Title        'The machine inactivity limit must be set to 15 minutes, locking the system with the screensaver.' `
        -Severity     'CAT_II' `
        -Description  'Unattended systems are susceptible to unauthorized use and must be locked when unattended. The screen saver must be set at a maximum of 15 minutes and be password protected. This protects critical and' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> InactivityTimeoutSecs' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Interactive logon: Machine inactivity limit`" to `"900`" secon' `
        -PassCriteria 'Value <= 900' `
        -Status       $status `
        -Evidence     "InactivityTimeoutSecs = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000070' 'The machine inactivity limit must be set to 15 minutes, locking the system with the screensaver.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000095
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScRemoveOption' -ErrorAction SilentlyContinue).ScRemoveOption
    $status = if ($null -ne $val -and [int]$val -ge 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000095' `
        -Title        'The Smart Card removal option must be configured to Force Logoff or Lock Workstation.' `
        -Severity     'CAT_II' `
        -Description  'Unattended systems are susceptible to unauthorized use and must be locked. Configuring a system to lock when a smart card is removed will ensure the system is inaccessible when unattended. <Documentab' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon -> ScRemoveOption' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Interactive logon: Smart card removal behavior`" to `"Lock Wor' `
        -PassCriteria 'Value >= 1' `
        -Status       $status `
        -Evidence     "ScRemoveOption = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000095' 'The Smart Card removal option must be configured to Force Logoff or Lock Workstation.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000100
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature' -ErrorAction SilentlyContinue).RequireSecuritySignature
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000100' `
        -Title        'The Windows SMB client must be configured to always perform SMB packet signing.' `
        -Severity     'CAT_II' `
        -Description  'The server message block (SMB) protocol provides the basis for many network operations. Digitally signed SMB packets aid in preventing man-in-the-middle attacks. If this policy is enabled, the SMB cli' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters -> RequireSecuritySignature' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Microsoft network client: Digitally sign communications (alway' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RequireSecuritySignature = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000100' 'The Windows SMB client must be configured to always perform SMB packet signing.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000110
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnablePlainTextPassword' -ErrorAction SilentlyContinue).EnablePlainTextPassword
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000110' `
        -Title        'Unencrypted passwords must not be sent to third-party SMB Servers.' `
        -Severity     'CAT_II' `
        -Description  'Some non-Microsoft SMB servers only support unencrypted (plain text) password authentication. Sending plain text passwords across the network, when authenticating to an SMB server, reduces the overall' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters -> EnablePlainTextPassword' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Microsoft network client: Send unencrypted password to third-p' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "EnablePlainTextPassword = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000110' 'Unencrypted passwords must not be sent to third-party SMB Servers.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000120
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RequireSecuritySignature' -ErrorAction SilentlyContinue).RequireSecuritySignature
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000120' `
        -Title        'The Windows SMB server must be configured to always perform SMB packet signing.' `
        -Severity     'CAT_II' `
        -Description  'The server message block (SMB) protocol provides the basis for many network operations. Digitally signed SMB packets aid in preventing man-in-the-middle attacks. If this policy is enabled, the SMB ser' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters -> RequireSecuritySignature' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Microsoft network server: Digitally sign communications (alway' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RequireSecuritySignature = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000120' 'The Windows SMB server must be configured to always perform SMB packet signing.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000145
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymousSAM' -ErrorAction SilentlyContinue).RestrictAnonymousSAM
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000145' `
        -Title        'Anonymous enumeration of SAM accounts must not be allowed.' `
        -Severity     'CAT_I' `
        -Description  'Anonymous enumeration of SAM accounts allows anonymous log on users (null session connections) to list all accounts names, thus providing a list of potential points to attack the system. f' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> RestrictAnonymousSAM' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network access: Do not allow anonymous enumeration of SAM acco' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RestrictAnonymousSAM = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000145' 'Anonymous enumeration of SAM accounts must not be allowed.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000150
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymous' -ErrorAction SilentlyContinue).RestrictAnonymous
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000150' `
        -Title        'Anonymous enumeration of shares must be restricted.' `
        -Severity     'CAT_I' `
        -Description  'Allowing anonymous logon users (null session connections) to list all account names and enumerate all shared resources can provide a map of potential points to attack the system. false</Do' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> RestrictAnonymous' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network access: Do not allow anonymous enumeration of SAM acco' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RestrictAnonymous = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000150' 'Anonymous enumeration of shares must be restricted.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000160
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'EveryoneIncludesAnonymous' -ErrorAction SilentlyContinue).EveryoneIncludesAnonymous
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000160' `
        -Title        'The system must be configured to prevent anonymous users from having the same rights as the Everyone group.' `
        -Severity     'CAT_II' `
        -Description  'Access by anonymous users must be restricted. If this setting is enabled, then anonymous users have the same rights and permissions as the built-in Everyone group. Anonymous users must not have these ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> EveryoneIncludesAnonymous' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network access: Let Everyone permissions apply to anonymous us' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "EveryoneIncludesAnonymous = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000160' 'The system must be configured to prevent anonymous users from having the same rights as the Everyone group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000165
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RestrictNullSessAccess' -ErrorAction SilentlyContinue).RestrictNullSessAccess
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000165' `
        -Title        'Anonymous access to Named Pipes and Shares must be restricted.' `
        -Severity     'CAT_I' `
        -Description  'Allowing anonymous access to named pipes or shares provides the potential for unauthorized system access. This setting restricts access to those defined in `"Network access: Named Pipes that can be ac' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters -> RestrictNullSessAccess' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network access: Restrict anonymous access to Named Pipes and S' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "RestrictNullSessAccess = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000165' 'Anonymous access to Named Pipes and Shares must be restricted.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000167
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'RestrictRemoteSAM' -ErrorAction SilentlyContinue).RestrictRemoteSAM
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000167' `
        -Title        'Remote calls to the Security Account Manager (SAM) must be restricted to Administrators.' `
        -Severity     'CAT_II' `
        -Description  'The Windows SAM stores users'' passwords. Restricting remote rpc connections to the SAM to Administrators helps protect those credentials.' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> RestrictRemoteSAM' `
        -Fix          'Navigate to the policy Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network access: Restrict clients allowed to make remote calls to SAM`"' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "RestrictRemoteSAM = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000167' 'Remote calls to the Security Account Manager (SAM) must be restricted to Administrators.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000180
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'allownullsessionfallback' -ErrorAction SilentlyContinue).allownullsessionfallback
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000180' `
        -Title        'NTLM must be prevented from falling back to a Null session.' `
        -Severity     'CAT_II' `
        -Description  'NTLM sessions that are allowed to fall back to Null (unauthenticated) sessions may gain unauthorized access.' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0 -> allownullsessionfallback' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Allow LocalSystem NULL session fallback`" to' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "allownullsessionfallback = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000180' 'NTLM must be prevented from falling back to a Null session.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000185
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u' -Name 'AllowOnlineID' -ErrorAction SilentlyContinue).AllowOnlineID
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000185' `
        -Title        'PKU2U authentication using online identities must be prevented.' `
        -Severity     'CAT_II' `
        -Description  'PKU2U is a peer-to-peer authentication protocol. This setting prevents online identities from authenticating to domain-joined systems. Authentication will be centrally managed with Windows user accoun' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u -> AllowOnlineID' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Allow PKU2U authentication requests to this ' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "AllowOnlineID = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000185' 'PKU2U authentication using online identities must be prevented.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000190
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'SupportedEncryptionTypes' -ErrorAction SilentlyContinue).SupportedEncryptionTypes
    $status = if ($val -eq 2147483640) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000190' `
        -Title        'Kerberos encryption types must be configured to prevent the use of DES and RC4 encryption suites.' `
        -Severity     'CAT_II' `
        -Description  'Certain encryption types are no longer considered secure. This setting configures a minimum encryption type for Kerberos, preventing the use of the DES and RC4 encryption suites. false</Do' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters -> SupportedEncryptionTypes' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Configure encryption types allowed for Kerbe' `
        -PassCriteria 'Value = 2147483640' `
        -Status       $status `
        -Evidence     "SupportedEncryptionTypes = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000190' 'Kerberos encryption types must be configured to prevent the use of DES and RC4 encryption suites.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000195
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'NoLMHash' -ErrorAction SilentlyContinue).NoLMHash
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000195' `
        -Title        'The system must be configured to prevent the storage of the LAN Manager hash of passwords.' `
        -Severity     'CAT_I' `
        -Description  'The LAN Manager hash uses a weak encryption algorithm and there are several tools available that use this hash to retrieve account passwords. This setting controls whether or not a LAN Manager hash of' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> NoLMHash' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Do not store LAN Manager hash value on next ' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "NoLMHash = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000195' 'The system must be configured to prevent the storage of the LAN Manager hash of passwords.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000205
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'LmCompatibilityLevel' -ErrorAction SilentlyContinue).LmCompatibilityLevel
    $status = if ($null -ne $val -and [int]$val -ge 5) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000205' `
        -Title        'The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM.' `
        -Severity     'CAT_I' `
        -Description  'The Kerberos v5 authentication protocol is the default for authentication of users who are logging on to domain accounts. NTLM, which is less secure, is retained in later Windows versions for compatib' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: LAN Manager authentication level`" to `"Send' `
        -PassCriteria 'Value >= 5' `
        -Status       $status `
        -Evidence     "LmCompatibilityLevel = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000205' 'The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000210
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LDAP' -Name 'LDAPClientIntegrity' -ErrorAction SilentlyContinue).LDAPClientIntegrity
    $status = if ($val -eq 2) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000210' `
        -Title        'The system must be configured to the required LDAP client signing level.' `
        -Severity     'CAT_II' `
        -Description  'This setting controls the signing requirements for LDAP clients. This setting must be set to Negotiate signing or Require signing, depending on the environment and type of LDAP server in use. <Documen' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP -> LDAPClientIntegrity' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: LDAP client signing requirements`" to `"Nego' `
        -PassCriteria 'Value = 2' `
        -Status       $status `
        -Evidence     "LDAPClientIntegrity = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000210' 'The system must be configured to the required LDAP client signing level.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000215
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinClientSec' -ErrorAction SilentlyContinue).NTLMMinClientSec
    $status = if ($val -eq 537395200) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000215' `
        -Title        'The system must be configured to meet the minimum session security requirement for NTLM SSP based clients.' `
        -Severity     'CAT_II' `
        -Description  'Microsoft has implemented a variety of security support providers for use with RPC sessions. All of the options must be enabled to ensure the maximum security level. false <M' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0 -> NTLMMinClientSec' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Minimum session security for NTLM SSP based ' `
        -PassCriteria 'Value = 537395200' `
        -Status       $status `
        -Evidence     "NTLMMinClientSec = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000215' 'The system must be configured to meet the minimum session security requirement for NTLM SSP based clients.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000220
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinServerSec' -ErrorAction SilentlyContinue).NTLMMinServerSec
    $status = if ($val -eq 537395200) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000220' `
        -Title        'The system must be configured to meet the minimum session security requirement for NTLM SSP based servers.' `
        -Severity     'CAT_II' `
        -Description  'Microsoft has implemented a variety of security support providers for use with RPC sessions. All of the options must be enabled to ensure the maximum security level. false <M' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0 -> NTLMMinServerSec' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Network security: Minimum session security for NTLM SSP based ' `
        -PassCriteria 'Value = 537395200' `
        -Status       $status `
        -Evidence     "NTLMMinServerSec = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000220' 'The system must be configured to meet the minimum session security requirement for NTLM SSP based servers.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000230
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'FIPSAlgorithmPolicy' -ErrorAction SilentlyContinue).FIPSAlgorithmPolicy
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000230' `
        -Title        'The system must be configured to use FIPS-compliant algorithms for encryption, hashing, and signing.' `
        -Severity     'CAT_II' `
        -Description  'This setting ensures that the system uses algorithms that are FIPS-compliant for encryption, hashing, and signing. FIPS-compliant algorithms meet specific standards established by the U.S. Government ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -> FIPSAlgorithmPolicy' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"System cryptography: Use FIPS compliant algorithms for encrypt' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "FIPSAlgorithmPolicy = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000230' 'The system must be configured to use FIPS-compliant algorithms for encryption, hashing, and signing.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000245
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'FilterAdministratorToken' -ErrorAction SilentlyContinue).FilterAdministratorToken
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000245' `
        -Title        'User Account Control approval mode for the built-in Administrator must be enabled.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting configures the built-in Administrator ac' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> FilterAdministratorToken' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Admin Approval Mode for the Built-in Adm' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "FilterAdministratorToken = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000245' 'User Account Control approval mode for the built-in Administrator must be enabled.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000250
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorAdmin' -ErrorAction SilentlyContinue).ConsentPromptBehaviorAdmin
    $status = if ($val -eq 2) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000250' `
        -Title        'User Account Control must prompt administrators for consent on the secure desktop.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting configures the elevation requirements fo' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> ConsentPromptBehaviorAdmin' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Behavior of the elevation prompt for adm' `
        -PassCriteria 'Value = 2' `
        -Status       $status `
        -Evidence     "ConsentPromptBehaviorAdmin = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000250' 'User Account Control must prompt administrators for consent on the secure desktop.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000255
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorUser' -ErrorAction SilentlyContinue).ConsentPromptBehaviorUser
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000255' `
        -Title        'User Account Control must automatically deny elevation requests for standard users.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. Denying elevation requests from standard user account' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> ConsentPromptBehaviorUser' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Behavior of the elevation prompt for sta' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "ConsentPromptBehaviorUser = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000255' 'User Account Control must automatically deny elevation requests for standard users.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000260
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableInstallerDetection' -ErrorAction SilentlyContinue).EnableInstallerDetection
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000260' `
        -Title        'User Account Control must be configured to detect application installations and prompt for elevation.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting requires Windows to respond to applicati' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> EnableInstallerDetection' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Detect application installations and pro' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "EnableInstallerDetection = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000260' 'User Account Control must be configured to detect application installations and prompt for elevation.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000265
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableSecureUIAPaths' -ErrorAction SilentlyContinue).EnableSecureUIAPaths
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000265' `
        -Title        'User Account Control must only elevate UIAccess applications that are installed in secure locations.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting configures Windows to only allow applica' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> EnableSecureUIAPaths' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Only elevate UIAccess applications that ' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "EnableSecureUIAPaths = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000265' 'User Account Control must only elevate UIAccess applications that are installed in secure locations.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000270
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA' -ErrorAction SilentlyContinue).EnableLUA
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000270' `
        -Title        'User Account Control must run all administrators in Admin Approval Mode, enabling UAC.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting enables UAC. false</Document' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> EnableLUA' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Run all administrators in Admin Approval' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "EnableLUA = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000270' 'User Account Control must run all administrators in Admin Approval Mode, enabling UAC.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000275
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableVirtualization' -ErrorAction SilentlyContinue).EnableVirtualization
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000275' `
        -Title        'User Account Control must virtualize file and registry write failures to per-user locations.' `
        -Severity     'CAT_II' `
        -Description  'User Account Control (UAC) is a security mechanism for limiting the elevation of privileges, including administrative accounts, unless authorized. This setting configures non-UAC compliant application' `
        -Check        'Registry: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -> EnableVirtualization' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"User Account Control: Virtualize file and registry write failu' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "EnableVirtualization = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000275' 'User Account Control must virtualize file and registry write failures to per-user locations.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000010
try {
    $guest = Get-LocalUser -Name 'Guest' -ErrorAction Stop
    $status = if (-not $guest.Enabled) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-SO-000010' 'Built-in Guest account must be disabled' 'CAT_II' 'Guest account provides unauthenticated access.' 'Get-LocalUser -Name Guest' 'Disable-LocalUser -Name Guest' 'Enabled = False' $status "Guest Enabled: $($guest.Enabled)"))
} catch { $findings.Add((New-Finding 'WN11-SO-000010' 'Guest account disabled' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-SO-000015
try {
    $localUsers = Get-LocalUser | Where-Object { $_.Enabled -and $_.PasswordRequired -eq $false -and $_.Name -ne 'DefaultAccount' }
    $status = if (@($localUsers).Count -eq 0) { 'Pass' } else { 'Fail' }
    $evidence = if (@($localUsers).Count -gt 0) { "Accounts with blank passwords: $(($localUsers | Select-Object -ExpandProperty Name) -join ',')" } else { 'No enabled accounts with blank passwords' }
    $findings.Add((New-Finding 'WN11-SO-000015' 'Accounts with blank passwords must be restricted' 'CAT_II' '' 'Get-LocalUser | Where-Object Enabled -and PasswordRequired -eq false' 'Set password requirement via secpol.msc or net user <name> *' 'No enabled accounts with blank passwords' $status $evidence))
} catch { $findings.Add((New-Finding 'WN11-SO-000015' 'Blank password accounts' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-SO-000020
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000020' `
        -Title        'The built-in administrator account must be renamed.' `
        -Severity     'CAT_II' `
        -Description  'The built-in administrator account is a well-known account subject to attack. Renaming this account to an unidentified name improves the protection of this account and the system. false</D' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Accounts: Rename administrator account`" to a name other than ' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000020' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000025
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000025' `
        -Title        'The built-in guest account must be renamed.' `
        -Severity     'CAT_II' `
        -Description  'The built-in guest account is a well-known user account on all Windows systems and, as initially installed, does not require a password. This can allow access to system resources by unauthorized users. Renaming this account to an unidentified name improves the protection of this acco' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"Accounts: Rename guest account`" to a name other than `"Guest`' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000025' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000085
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000085' `
        -Title        'Caching of logon credentials must be limited.' `
        -Severity     'CAT_III' `
        -Description  'The default Windows configuration caches the last logon credentials for users who log on interactively to a system. This feature is provided for system availability reasons, such as the user''s machine being disconnected from the network or domain controllers being unavailable.' `
        -Check        '' `
        -Fix          'This is the default configuration for this setting (10 logons to cache). Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Op' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000085' 'Error' 'CAT_III' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000240
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000240' `
        -Title        'The default permissions of global system objects must be increased.' `
        -Severity     'CAT_III' `
        -Description  'Windows systems maintain a global list of shared system resources such as DOS device names, mutexes, and semaphores. Each type of object is created with a default DACL that specifies who can access the objects with what permissions. If this policy is enabled, the default DACL is stro' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options >> `"System objects: Strengthen default permissions of internal sys' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000240' 'Error' 'CAT_III' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-SO-000251
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-SO-000251' `
        -Title        'Windows 11 must use multifactor authentication for local and network access to privileged and nonprivileged accounts.' `
        -Severity     'CAT_II' `
        -Description  'Without the use of multifactor authentication, the ease of access to privileged and nonprivileged functions is greatly increased. All domain accounts must be enabled for multifactor authentication with the exception of local emergency accounts. Multifactor authentication requires usi' `
        -Check        '' `
        -Fix          'For nondomain joined systems, configuring Windows Hello for sign-on options would be suggested based on the organization''s needs and capabilities.' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-SO-000251' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
return $findings
