#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-UR-* : User Rights Assignment
# ==========================================================

# Export security policy once for all URA checks
$_secTmp = "$env:TEMP\ura_$PID.cfg"
$_secLines = $null
try {
    secedit /export /cfg $_secTmp /quiet 2>&1 | Out-Null
    $_secLines = Get-Content $_secTmp -ErrorAction Stop
    Remove-Item $_secTmp -Force -ErrorAction SilentlyContinue
} catch { Write-Warning "secedit export failed: $_" }

function _GetPrivRight([string]$Priv) {
    if ($null -eq $_secLines) { return 'EXPORT_FAILED' }
    $line = $_secLines | Where-Object { $_ -match "^$Priv\s*=" }
    if ($line) { ($line -split '=',2)[1].Trim() } else { '' }
}

# WN11-UR-000005
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000005' `
        -Title        'The "Access Credential Manager as a trusted caller" user right must not be assigned to any groups or accounts.' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. Accounts with the `"Access Credential Manager as a trusted caller`" user right may be able to retrieve the credentials of other accounts from Credential Manager.</VulnDiscussion' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Access Credential Manager as a trusted caller`" to be de' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000005' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000010
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000010' `
        -Title        'The "Access this computer from the network" user right must only be assigned to the Administrators and Remote Desktop Us' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. Accounts with the `"Access this computer from the network`" user right may access resources on the system, and must be limited to those that require it. <FalsePo' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Access this computer from the network`" to only include ' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000010' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000015
try {
    $val = _GetPrivRight 'SeTcbPrivilege'
    $status = if ([string]::IsNullOrWhiteSpace($val) -or $val -eq 'EXPORT_FAILED') { if ($val -eq 'EXPORT_FAILED') { 'Error' } else { 'Pass' } } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000015' 'The "Act as part of the operating system" user right must not be assigned to any groups or accounts.' 'CAT_I' '' 'secedit export -> SeTcbPrivilege' 'Remove all entries from User Rights Assignment for SeTcbPrivilege' 'SeTcbPrivilege must be empty' $status "SeTcbPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000015' 'The "Act as part of the operating system" user right must not be assigned to any groups or accounts.' 'CAT_I' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000025
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000025' `
        -Title        'The "Allow log on locally" user right must only be assigned to the Administrators and Users groups.' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. Accounts with the `"Allow log on locally`" user right can log on interactively to a system. <Do' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Allow log on locally`" to only include the following gro' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000025' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000030
try {
    $val = _GetPrivRight 'SeBackupPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000030' 'The "Back up files and directories" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeBackupPrivilege' 'Restrict SeBackupPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeBackupPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000030' 'The "Back up files and directories" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000035
try {
    $val = _GetPrivRight 'SeSystemtimePrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544','*S-1-5-19')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000035' 'The "Change the system time" user right must only be assigned to Administrators and Local Service.' 'CAT_II' '' 'secedit export -> SeSystemtimePrivilege' 'Restrict SeSystemtimePrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeSystemtimePrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000035' 'The "Change the system time" user right must only be assigned to Administrators and Local Service.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000040
try {
    $val = _GetPrivRight 'SeCreatePagefilePrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000040' 'The "Create a pagefile" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeCreatePagefilePrivilege' 'Restrict SeCreatePagefilePrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeCreatePagefilePrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000040' 'The "Create a pagefile" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000045
try {
    $val = _GetPrivRight 'SeCreateTokenPrivilege'
    $status = if ([string]::IsNullOrWhiteSpace($val) -or $val -eq 'EXPORT_FAILED') { if ($val -eq 'EXPORT_FAILED') { 'Error' } else { 'Pass' } } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000045' 'The "Create a token object" user right must not be assigned to any groups or accounts.' 'CAT_I' '' 'secedit export -> SeCreateTokenPrivilege' 'Remove all entries from User Rights Assignment for SeCreateTokenPrivilege' 'SeCreateTokenPrivilege must be empty' $status "SeCreateTokenPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000045' 'The "Create a token object" user right must not be assigned to any groups or accounts.' 'CAT_I' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000050
try {
    $val = _GetPrivRight 'SeCreateGlobalPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544','*S-1-5-6','*S-1-5-20','*S-1-5-19')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000050' 'The "Create global objects" user right must only be assigned to Administrators, Service, Local Service, and Network Serv' 'CAT_II' '' 'secedit export -> SeCreateGlobalPrivilege' 'Restrict SeCreateGlobalPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeCreateGlobalPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000050' 'The "Create global objects" user right must only be assigned to Administrators, Service, Local Service, and Network Serv' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000055
try {
    $val = _GetPrivRight 'SeCreatePermanentPrivilege'
    $status = if ([string]::IsNullOrWhiteSpace($val) -or $val -eq 'EXPORT_FAILED') { if ($val -eq 'EXPORT_FAILED') { 'Error' } else { 'Pass' } } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000055' 'The "Create permanent shared objects" user right must not be assigned to any groups or accounts.' 'CAT_II' '' 'secedit export -> SeCreatePermanentPrivilege' 'Remove all entries from User Rights Assignment for SeCreatePermanentPrivilege' 'SeCreatePermanentPrivilege must be empty' $status "SeCreatePermanentPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000055' 'The "Create permanent shared objects" user right must not be assigned to any groups or accounts.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000060
try {
    $val = _GetPrivRight 'SeCreateSymbolicLinkPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000060' 'The "Create symbolic links" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeCreateSymbolicLinkPrivilege' 'Restrict SeCreateSymbolicLinkPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeCreateSymbolicLinkPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000060' 'The "Create symbolic links" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000065
try {
    $val = _GetPrivRight 'SeDebugPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000065' 'The "Debug programs" user right must only be assigned to the Administrators group.' 'CAT_I' '' 'secedit export -> SeDebugPrivilege' 'Restrict SeDebugPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeDebugPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000065' 'The "Debug programs" user right must only be assigned to the Administrators group.' 'CAT_I' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000070
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000070' `
        -Title        'The "Deny access to this computer from the network" user right on workstations must be configured to prevent access from' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. The `"Deny access to this computer from the network`" right defines the accounts that are prevented from logging on from the network. In an Active Directory Domain, denying logo' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Deny access to this computer from the network`" to inclu' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000070' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000075
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000075' `
        -Title        'The "Deny log on as a batch job" user right on domain-joined workstations must be configured to prevent access from high' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. The `"Deny log on as a batch job`" right defines accounts that are prevented from logging on to the system as a batch job, such as Task Scheduler. In an Active Directory Domain,' `
        -Check        '' `
        -Fix          'This requirement is applicable to domain-joined systems, for standalone systems this is NA. Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Poli' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000075' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000080
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000080' `
        -Title        'The "Deny log on as a service" user right on Windows 11 domain-joined workstations must be configured to prevent access ' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. The `"Deny log on as a service`" right defines accounts that are denied log on as a service. In an Active Directory Domain, denying logons to the Enterprise Admins and Domain Ad' `
        -Check        '' `
        -Fix          'This requirement is applicable to domain-joined systems, for standalone systems this is NA. Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Poli' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000080' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000085
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000085' `
        -Title        'The "Deny log on locally" user right on workstations must be configured to prevent access from highly privileged domain ' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. The `"Deny log on locally`" right defines accounts that are prevented from logging on interactively. In an Active Directory Domain, denying logons to the Enterprise Admins and D' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Deny log on locally`" to include the following: Domain S' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000085' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000090
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-UR-000090' `
        -Title        'The "Deny log on through Remote Desktop Services" user right on Windows 11 workstations must be configured to prevent ac' `
        -Severity     'CAT_II' `
        -Description  'Inappropriate granting of user rights can provide system, administrative, and other high-level capabilities. The `"Deny log on through Remote Desktop Services`" right defines the accounts that are prevented from logging on using Remote Desktop Services. If Remote Desktop Services is no' `
        -Check        '' `
        -Fix          'Configure the policy value for Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> User Rights Assignment >> `"Deny log on through Remote Desktop Services`" to include' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UR-000090' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UR-000095
try {
    $val = _GetPrivRight 'SeEnableDelegationPrivilege'
    $status = if ([string]::IsNullOrWhiteSpace($val) -or $val -eq 'EXPORT_FAILED') { if ($val -eq 'EXPORT_FAILED') { 'Error' } else { 'Pass' } } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000095' 'The "Enable computer and user accounts to be trusted for delegation" user right must not be assigned to any groups or ac' 'CAT_II' '' 'secedit export -> SeEnableDelegationPrivilege' 'Remove all entries from User Rights Assignment for SeEnableDelegationPrivilege' 'SeEnableDelegationPrivilege must be empty' $status "SeEnableDelegationPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000095' 'The "Enable computer and user accounts to be trusted for delegation" user right must not be assigned to any groups or ac' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000100
try {
    $val = _GetPrivRight 'SeRemoteShutdownPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000100' 'The "Force shutdown from a remote system" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeRemoteShutdownPrivilege' 'Restrict SeRemoteShutdownPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeRemoteShutdownPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000100' 'The "Force shutdown from a remote system" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000110
try {
    $val = _GetPrivRight 'SeImpersonatePrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544','*S-1-5-6','*S-1-5-20','*S-1-5-19')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000110' 'The "Impersonate a client after authentication" user right must only be assigned to Administrators, Service, Local Servi' 'CAT_II' '' 'secedit export -> SeImpersonatePrivilege' 'Restrict SeImpersonatePrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeImpersonatePrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000110' 'The "Impersonate a client after authentication" user right must only be assigned to Administrators, Service, Local Servi' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000120
try {
    $val = _GetPrivRight 'SeLoadDriverPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000120' 'The "Load and unload device drivers" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeLoadDriverPrivilege' 'Restrict SeLoadDriverPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeLoadDriverPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000120' 'The "Load and unload device drivers" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000125
try {
    $val = _GetPrivRight 'SeLockMemoryPrivilege'
    $status = if ([string]::IsNullOrWhiteSpace($val) -or $val -eq 'EXPORT_FAILED') { if ($val -eq 'EXPORT_FAILED') { 'Error' } else { 'Pass' } } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000125' 'The "Lock pages in memory" user right must not be assigned to any groups or accounts.' 'CAT_II' '' 'secedit export -> SeLockMemoryPrivilege' 'Remove all entries from User Rights Assignment for SeLockMemoryPrivilege' 'SeLockMemoryPrivilege must be empty' $status "SeLockMemoryPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000125' 'The "Lock pages in memory" user right must not be assigned to any groups or accounts.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000130
try {
    $val = _GetPrivRight 'SeSecurityPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000130' 'The "Manage auditing and security log" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeSecurityPrivilege' 'Restrict SeSecurityPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeSecurityPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000130' 'The "Manage auditing and security log" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000140
try {
    $val = _GetPrivRight 'SeSystemEnvironmentPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000140' 'The "Modify firmware environment values" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeSystemEnvironmentPrivilege' 'Restrict SeSystemEnvironmentPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeSystemEnvironmentPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000140' 'The "Modify firmware environment values" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000145
try {
    $val = _GetPrivRight 'SeManageVolumePrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000145' 'The "Perform volume maintenance tasks" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeManageVolumePrivilege' 'Restrict SeManageVolumePrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeManageVolumePrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000145' 'The "Perform volume maintenance tasks" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000150
try {
    $val = _GetPrivRight 'SeProfileSingleProcessPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000150' 'The "Profile single process" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeProfileSingleProcessPrivilege' 'Restrict SeProfileSingleProcessPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeProfileSingleProcessPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000150' 'The "Profile single process" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000160
try {
    $val = _GetPrivRight 'SeRestorePrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000160' 'The "Restore files and directories" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeRestorePrivilege' 'Restrict SeRestorePrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeRestorePrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000160' 'The "Restore files and directories" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-UR-000165
try {
    $val = _GetPrivRight 'SeTakeOwnershipPrivilege'
    $assigned = if ($val) { $val -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } } else { @() }
    $allowed  = @('*S-1-5-32-544')
    $unexp    = @($assigned | Where-Object { $_ -notin $allowed })
    $status   = if ($unexp.Count -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-UR-000165' 'The "Take ownership of files or other objects" user right must only be assigned to the Administrators group.' 'CAT_II' '' 'secedit export -> SeTakeOwnershipPrivilege' 'Restrict SeTakeOwnershipPrivilege to allowed principals only' 'Only allowed SIDs assigned' $status "SeTakeOwnershipPrivilege = $(if ($val) { $val } else { '(empty)' })"))
} catch { $findings.Add((New-Finding 'WN11-UR-000165' 'The "Take ownership of files or other objects" user right must only be assigned to the Administrators group.' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
return $findings
