#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-00-* : General System Controls
# ==========================================================

# WN11-00-000005
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000005' `
        -Title        'Domain-joined systems must use Windows 11 Enterprise Edition 64-bit version.' `
        -Severity     'CAT_II' `
        -Description  'Features such as Credential Guard use virtualization-based security to protect information that could be used in credential theft attacks if compromised. There are a number of system requirements that must be met in order for Credential Guard to be configured and enabled properly. Vi' `
        -Check        '' `
        -Fix          'Use Windows 11 Enterprise 64-bit version for domain-joined systems.' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000005' 'Error' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000030
try {
    $blVol = Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction Stop
    $status = if ($blVol.ProtectionStatus -eq 'On') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000030' `
        -Title        'BitLocker must protect the OS drive' `
        -Severity     'CAT_I' `
        -Description  'If data at rest is unencrypted, it is vulnerable to disclosure.' `
        -Check        'Get-BitLockerVolume -MountPoint $env:SystemDrive' `
        -Fix          'Enable-BitLocker -MountPoint C: -EncryptionMethod XtsAes256 -TpmProtector' `
        -PassCriteria 'ProtectionStatus = On' `
        -Status       $status `
        -Evidence     "Protection: $($blVol.ProtectionStatus) | Volume: $($blVol.VolumeStatus)"
    ))
} catch {
    try {
        $bde = manage-bde -status $env:SystemDrive 2>&1
        $line = $bde | Where-Object { $_ -match 'Protection Status' }
        $status = if ($line -and $line -match 'Protection On') { 'Pass' } else { 'Fail' }
        $findings.Add((New-Finding 'WN11-00-000030' 'BitLocker must protect the OS drive' 'CAT_I' '' 'manage-bde -status C:' 'manage-bde -on C: -RecoveryPassword' 'Protection On' $status (($line | Out-String).Trim())))
    } catch {
        $findings.Add((New-Finding 'WN11-00-000030' 'BitLocker OS drive' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
    }
}
# WN11-00-000031
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'UseTPMPIN' -ErrorAction SilentlyContinue).UseTPMPIN
    $status = if ($null -ne $val -and [int]$val -ge 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000031' `
        -Title        'Windows 11 systems must use a BitLocker PIN for pre-boot authentication.' `
        -Severity     'CAT_I' `
        -Description  'If data at rest is unencrypted, it is vulnerable to disclosure. Even if the operating system enforces permissions on data access, an adversary can remove non-volatile memory and read it directly, ther' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\FVE -> UseTPMPIN' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> Windows Components >> BitLocker Drive Encryption >> Operating System Drives `"Require additional authentication at ' `
        -PassCriteria 'Value >= 1' `
        -Status       $status `
        -Evidence     "UseTPMPIN = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000031' 'Windows 11 systems must use a BitLocker PIN for pre-boot authentication.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000032
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'MinimumPIN' -ErrorAction SilentlyContinue).MinimumPIN
    $status = if ($null -ne $val -and [int]$val -ge 6) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000032' `
        -Title        'Windows 11 systems must use a BitLocker PIN with a minimum length of six digits for pre-boot authentication.' `
        -Severity     'CAT_II' `
        -Description  'If data at rest is unencrypted, it is vulnerable to disclosure. Even if the operating system enforces permissions on data access, an adversary can remove non-volatile memory and read it directly, ther' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\FVE -> MinimumPIN' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> Windows Components >> BitLocker Drive Encryption >> Operating System Drives `"Configure minimum PIN length for star' `
        -PassCriteria 'Value >= 6' `
        -Status       $status `
        -Evidence     "MinimumPIN = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000032' 'Windows 11 systems must use a BitLocker PIN with a minimum length of six digits for pre-boot authentication.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000040
try {
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000040' `
        -Title        'Windows 11 systems must be maintained at a supported servicing level.' `
        -Severity     'CAT_I' `
        -Description  'Windows 11 is maintained by Microsoft at servicing levels for specific periods of time to support Windows as a Service. Systems at unsupported servicing levels or releases will not receive security updates for new vulnerabilities which leaves them subject to exploitation. New version' `
        -Check        '' `
        -Fix          'Update systems on the Semi-Annual Channel to `"Microsoft Windows 11 Version 22H2 (OS Build 22621.380)`" or greater.' `
        -PassCriteria 'Manual verification required' `
        -Status       'Manual' `
        -Evidence     'Requires manual review'
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000040' 'Error' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000050
try {
    $nonNTFS = Get-Volume | Where-Object { $_.DriveType -eq 'Fixed' -and $_.FileSystemType -ne 'NTFS' -and $_.DriveLetter }
    $status  = if (@($nonNTFS).Count -eq 0) { 'Pass' } else { 'Fail' }
    $evidence = if (@($nonNTFS).Count -gt 0) { "Non-NTFS volumes: $(($nonNTFS | Select-Object -ExpandProperty DriveLetter) -join ',')" } else { 'All fixed volumes are NTFS' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000050' `
        -Title        'Local volumes must be formatted using NTFS' `
        -Severity     'CAT_I' `
        -Description  'NTFS is required for proper access control enforcement.' `
        -Check        'Get-Volume | Where-Object { DriveType -eq Fixed -and FileSystemType -ne NTFS }' `
        -Fix          'Convert non-NTFS fixed volumes to NTFS: convert <drive>: /fs:ntfs' `
        -PassCriteria 'No fixed volumes with non-NTFS filesystem' `
        -Status       $status `
        -Evidence     $evidence
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000050' 'NTFS volumes' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000100
try {
    $iis = Get-WindowsOptionalFeature -Online -FeatureName 'IIS-WebServerRole' -ErrorAction SilentlyContinue
    $status = if ($null -eq $iis -or $iis.State -ne 'Enabled') { 'Pass' } else { 'Fail' }
    $evidence = if ($null -ne $iis) { "IIS-WebServerRole State: $($iis.State)" } else { 'Feature not found (not installed)' }
    $findings.Add((New-Finding 'WN11-00-000100' 'IIS must not be installed' 'CAT_I' 'IIS is a server role and must not run on a workstation.' 'Get-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole' 'Disable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole' 'State != Enabled' $status $evidence))
} catch {
    $findings.Add((New-Finding 'WN11-00-000100' 'IIS not installed' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000110
try {
    $feat = Get-WindowsOptionalFeature -Online -FeatureName 'SimpleTCPIP' -ErrorAction SilentlyContinue
    $status = if ($null -eq $feat -or $feat.State -ne 'Enabled') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000110' 'Simple TCP/IP Services must not be installed' 'CAT_II' '' 'Get-WindowsOptionalFeature SimpleTCPIP' 'Disable-WindowsOptionalFeature -Online -FeatureName SimpleTCPIP' 'State != Enabled' $status "State: $(if ($feat) { $feat.State } else { 'Not Found' })"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000110' 'Simple TCP/IP Services' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000115
try {
    $feat = Get-WindowsOptionalFeature -Online -FeatureName 'TelnetClient' -ErrorAction SilentlyContinue
    $status = if ($null -eq $feat -or $feat.State -ne 'Enabled') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000115' 'Telnet Client must not be installed' 'CAT_II' '' 'Get-WindowsOptionalFeature TelnetClient' 'Disable-WindowsOptionalFeature -Online -FeatureName TelnetClient' 'State != Enabled' $status "State: $(if ($feat) { $feat.State } else { 'Not Found' })"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000115' 'Telnet Client' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000120
try {
    $feat = Get-WindowsOptionalFeature -Online -FeatureName 'TFTP' -ErrorAction SilentlyContinue
    $status = if ($null -eq $feat -or $feat.State -ne 'Enabled') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000120' 'TFTP Client must not be installed' 'CAT_II' '' 'Get-WindowsOptionalFeature TFTP' 'Disable-WindowsOptionalFeature -Online -FeatureName TFTP' 'State != Enabled' $status "State: $(if ($feat) { $feat.State } else { 'Not Found' })"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000120' 'TFTP Client' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000150
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel' -Name 'DisableExceptionChainValidation' -ErrorAction SilentlyContinue).DisableExceptionChainValidation
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000150' `
        -Title        'Structured Exception Handling Overwrite Protection (SEHOP) must be enabled.' `
        -Severity     'CAT_I' `
        -Description  'Attackers are constantly looking for vulnerabilities in systems and applications. Structured Exception Handling Overwrite Protection (SEHOP) blocks exploits that use the Structured Exception Handling ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel -> DisableExceptionChainValidation' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> MS Security Guide >> `"Enable Structured Exception Handling Overwrite Protection (SEHOP)`" to `"Enabled`". This pol' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "DisableExceptionChainValidation = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000150' 'Structured Exception Handling Overwrite Protection (SEHOP) must be enabled.' 'CAT_I' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000155
try {
    $feat = Get-WindowsOptionalFeature -Online -FeatureName 'MicrosoftWindowsPowerShellV2Root' -ErrorAction SilentlyContinue
    $status = if ($null -eq $feat -or $feat.State -ne 'Enabled') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000155' 'PowerShell 2.0 must be disabled' 'CAT_II' 'PS 2.0 bypasses execution policy, logging, and AMSI.' 'Get-WindowsOptionalFeature MicrosoftWindowsPowerShellV2Root' 'Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root' 'State != Enabled' $status "State: $(if ($feat) { $feat.State } else { 'Not Found' })"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000155' 'PowerShell 2.0 disabled' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000160
try {
    $smb1 = (Get-SmbServerConfiguration -ErrorAction Stop).EnableSMB1Protocol
    $status = if (-not $smb1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000160' 'SMB v1 must be disabled on the system' 'CAT_II' 'SMBv1 is critically vulnerable (EternalBlue/WannaCry).' 'Get-SmbServerConfiguration | Select EnableSMB1Protocol' 'Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force' 'EnableSMB1Protocol = False' $status "EnableSMB1Protocol: $smb1"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000160' 'SMB v1 server disabled' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000165
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10' -Name 'Start' -ErrorAction SilentlyContinue).Start
    $status = if ($val -eq 4) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000165' `
        -Title        'The Server Message Block (SMB) v1 protocol must be disabled on the SMB server.' `
        -Severity     'CAT_II' `
        -Description  'SMBv1 is a legacy protocol that uses the MD5 algorithm as part of SMB. MD5 is known to be vulnerable to a number of attacks such as collision and preimage attacks as well as not being FIPS compliant. ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10 -> Start' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> MS Security Guide >> `"Configure SMBv1 Server`" to `"Disabled`". This policy setting requires the installation of t' `
        -PassCriteria 'Value = 4' `
        -Status       $status `
        -Evidence     "Start = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000165' 'The Server Message Block (SMB) v1 protocol must be disabled on the SMB server.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000170
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'SMB1' -ErrorAction SilentlyContinue).SMB1
    $status = if ($val -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000170' `
        -Title        'The Server Message Block (SMB) v1 protocol must be disabled on the SMB client.' `
        -Severity     'CAT_II' `
        -Description  'SMBv1 is a legacy protocol that uses the MD5 algorithm as part of SMB. MD5 is known to be vulnerable to a number of attacks such as collision and preimage attacks as well as not being FIPS compliant. ' `
        -Check        'Registry: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters -> SMB1' `
        -Fix          'Configure the policy value for Computer Configuration >> Administrative Templates >> MS Security Guide >> `"Configure SMBv1 client driver`" to `"Enabled`" with `"Disable driver (recommended)`" selecte' `
        -PassCriteria 'Value = 0' `
        -Status       $status `
        -Evidence     "SMB1 = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000170' 'The Server Message Block (SMB) v1 protocol must be disabled on the SMB client.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000175
try {
    $svc = Get-Service -Name 'seclogon' -ErrorAction Stop
    $status = if ($svc.StartType -eq 'Disabled') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-00-000175' 'Secondary Logon service must be disabled' 'CAT_II' 'Secondary Logon allows running programs under different credentials, enabling lateral movement.' 'Get-Service seclogon' 'Set-Service -Name seclogon -StartupType Disabled; Stop-Service seclogon -Force' 'StartType = Disabled' $status "StartType: $($svc.StartType) | Status: $($svc.Status)"))
} catch {
    $findings.Add((New-Finding 'WN11-00-000175' 'Secondary Logon service' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-00-000126
try {
    $val = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftAccount' -Name 'DisableUserAuth' -ErrorAction SilentlyContinue).DisableUserAuth
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-00-000126' `
        -Title        'Windows 11 systems must block consumer account user authentication.' `
        -Severity     'CAT_II' `
        -Description  'It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives. These unnecessary capabilities or services are often overlooked a' `
        -Check        'Registry: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftAccount -> DisableUserAuth' `
        -Fix          'Configure the following Group Policy: Computer Configuration >> Administrative Templates >> Windows Components >> Microsoft Account `"block all consumer Microsoft account user authentication`" to `"En' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "DisableUserAuth = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-00-000126' 'Windows 11 systems must block consumer account user authentication.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
return $findings
