#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-UC-* : User Configuration / Miscellaneous
# ==========================================================

# WN11-UC-000020
try {
    $val = (Get-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments' -Name 'SaveZoneInformation' -ErrorAction SilentlyContinue).SaveZoneInformation
    $status = if ($val -eq 2) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-UC-000020' `
        -Title        'Zone information must be preserved when saving attachments.' `
        -Severity     'CAT_II' `
        -Description  'Preserving zone of origin (internet, intranet, local, restricted) information on file attachments allows Windows to determine risk. false <Severity' `
        -Check        'Registry: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments -> SaveZoneInformation' `
        -Fix          'The default behavior is for Windows to mark file attachments with their zone information. To correct this, configure the policy value for User Configuration >> Administrative Templates >> Windows Comp' `
        -PassCriteria 'Value = 2' `
        -Status       $status `
        -Evidence     "SaveZoneInformation = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UC-000020' 'Zone information must be preserved when saving attachments.' 'CAT_II' '' '' '' '' 'Error' $_.ToString()))
}
# WN11-UC-000015
try {
    $val = (Get-ItemProperty -Path 'HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications' -Name 'NoToastApplicationNotificationOnLockScreen' -ErrorAction SilentlyContinue).NoToastApplicationNotificationOnLockScreen
    $status = if ($val -eq 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding `
        -StigId       'WN11-UC-000015' `
        -Title        'Toast notifications to the lock screen must be turned off.' `
        -Severity     'CAT_III' `
        -Description  'Toast notifications that are displayed on the lock screen could display sensitive information to unauthorized personnel. Turning off this feature will limit access to the information to a logged on us' `
        -Check        'Registry: HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications -> NoToastApplicationNotificationOnLockScreen' `
        -Fix          'Configure the policy value for User Configuration >> Administrative Templates >> Start Menu and Taskbar >> Notifications >> `"Turn off toast notifications on the lock screen`" to `"Enabled`".' `
        -PassCriteria 'Value = 1' `
        -Status       $status `
        -Evidence     "NoToastApplicationNotificationOnLockScreen = $(if (`$null -ne `$val) { `$val } else { 'NOT SET' })"
    ))
} catch {
    $findings.Add((New-Finding 'WN11-UC-000015' 'Toast notifications to the lock screen must be turned off.' 'CAT_III' '' '' '' '' 'Error' $_.ToString()))
}
return $findings
