#Requires -Version 5.0
# AUTO-GENERATED from DISA STIG WN11 V2R8 (U_MS_Windows_11_V2R8_STIG_SCAP_1-3_Benchmark.xml)
# Generated by CyberBook assessment tool.

$findings = [System.Collections.Generic.List[PSObject]]::new()

function New-Finding {
    param($StigId,$Title,$Severity,$Description,$Check,$Fix,$PassCriteria,$Status,$Evidence="")
    [PSCustomObject]@{
        stig_id       = $StigId
        title         = $Title
        severity      = $Severity
        description   = $Description
        check         = $Check
        fix           = $Fix
        pass_criteria = $PassCriteria
        status        = $Status
        evidence      = $Evidence
    }
}

# ==========================================================
# WN11-AC-* : Account / Password Policy
# ==========================================================

# Helper (local to this module run)
$_netAccts = net accounts 2>&1
function _GetNetVal([string]$Label) {
    $line = $_netAccts | Where-Object { $_ -match $Label }
    if ($line) { ($line -split ':',2)[1].Trim() } else { 'UNKNOWN' }
}
function _GetNetInt([string]$Label, [int]$Default=0) {
    $v = _GetNetVal $Label
    if ($v -match '^\d+$') { [int]$v } else { $Default }
}

# WN11-AC-000005
try {
    $dur = _GetNetInt 'Lockout duration' 0
    $status = if ($dur -ge 15 -or $dur -eq 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000005' 'Account lockout duration must be 15 minutes or more' 'CAT_II' '' 'net accounts | find "Lockout duration"' 'net accounts /lockoutduration:15' 'Value >= 15 or 0 (never auto-unlock)' $status "Lockout duration: $dur minutes"))
} catch { $findings.Add((New-Finding 'WN11-AC-000005' 'Lockout duration' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000010
try {
    $thr = _GetNetInt 'Lockout threshold' 999
    $status = if ($thr -ge 1 -and $thr -le 3) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000010' 'Account lockout threshold must be 3 or fewer invalid attempts' 'CAT_II' '' 'net accounts | find "Lockout threshold"' 'net accounts /lockoutthreshold:3' '1 <= Value <= 3' $status "Lockout threshold: $thr"))
} catch { $findings.Add((New-Finding 'WN11-AC-000010' 'Lockout threshold' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000015
try {
    $win = _GetNetInt 'Lockout observation window' 0
    $status = if ($win -ge 15) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000015' 'Reset account lockout counter must be 15 minutes or more' 'CAT_II' '' 'net accounts | find "Lockout observation window"' 'net accounts /lockoutwindow:15' 'Value >= 15' $status "Observation window: $win minutes"))
} catch { $findings.Add((New-Finding 'WN11-AC-000015' 'Lockout observation window' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000020
try {
    $hist = _GetNetInt 'Length of password history' 0
    $status = if ($hist -ge 24) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000020' 'Password history must be 24 passwords' 'CAT_II' '' 'net accounts | find "Length of password history"' 'net accounts /uniquepw:24' 'Value >= 24' $status "Password history: $hist"))
} catch { $findings.Add((New-Finding 'WN11-AC-000020' 'Password history' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000025
try {
    $maxAge = _GetNetInt 'Maximum password age' 999
    $status = if ($maxAge -le 60 -and $maxAge -gt 0) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000025' 'Maximum password age must be 60 days or less' 'CAT_II' '' 'net accounts | find "Maximum password age"' 'net accounts /maxpwage:60' '0 < Value <= 60' $status "Maximum password age: $maxAge days"))
} catch { $findings.Add((New-Finding 'WN11-AC-000025' 'Max password age' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000030
try {
    $minAge = _GetNetInt 'Minimum password age' 0
    $status = if ($minAge -ge 1) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000030' 'Minimum password age must be at least 1 day' 'CAT_II' '' 'net accounts | find "Minimum password age"' 'net accounts /minpwage:1' 'Value >= 1' $status "Minimum password age: $minAge days"))
} catch { $findings.Add((New-Finding 'WN11-AC-000030' 'Min password age' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000035
try {
    $minLen = _GetNetInt 'Minimum password length' 0
    $status = if ($minLen -ge 14) { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000035' 'Passwords must be at least 14 characters' 'CAT_II' '' 'net accounts | find "Minimum password length"' 'net accounts /minpwlen:14' 'Value >= 14' $status "Minimum password length: $minLen"))
} catch { $findings.Add((New-Finding 'WN11-AC-000035' 'Min password length' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000040
try {
    $tmpCfg = "$env:TEMP\pwcmplx_$PID.cfg"
    secedit /export /cfg $tmpCfg /quiet 2>&1 | Out-Null
    $lines = Get-Content $tmpCfg -ErrorAction Stop
    Remove-Item $tmpCfg -Force -ErrorAction SilentlyContinue
    $line = $lines | Where-Object { $_ -match 'PasswordComplexity\s*=' }
    $val  = if ($line) { ($line -split '=',2)[1].Trim() } else { '0' }
    $status = if ($val -eq '1') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000040' 'Password complexity filter must be enabled' 'CAT_II' '' 'secedit /export -> PasswordComplexity' 'Enable via Security Policy: Password must meet complexity requirements' 'PasswordComplexity = 1' $status "PasswordComplexity = $val"))
} catch { $findings.Add((New-Finding 'WN11-AC-000040' 'Password complexity' 'CAT_II' '' '' '' '' 'Error' $_.ToString())) }
# WN11-AC-000045
try {
    $tmpCfg = "$env:TEMP\revenc_$PID.cfg"
    secedit /export /cfg $tmpCfg /quiet 2>&1 | Out-Null
    $lines = Get-Content $tmpCfg -ErrorAction Stop
    Remove-Item $tmpCfg -Force -ErrorAction SilentlyContinue
    $line = $lines | Where-Object { $_ -match 'ClearTextPassword\s*=' }
    $val  = if ($line) { ($line -split '=',2)[1].Trim() } else { '0' }
    $status = if ($val -eq '0') { 'Pass' } else { 'Fail' }
    $findings.Add((New-Finding 'WN11-AC-000045' 'Reversible password encryption must be disabled' 'CAT_I' 'Reversible encryption stores passwords in a recoverable form.' 'secedit /export -> ClearTextPassword' 'Disable via Security Policy: Store passwords using reversible encryption = Disabled' 'ClearTextPassword = 0' $status "ClearTextPassword = $val"))
} catch { $findings.Add((New-Finding 'WN11-AC-000045' 'Reversible password encryption' 'CAT_I' '' '' '' '' 'Error' $_.ToString())) }
return $findings
